// Sonic Pi SynthDefs for SuperSonic
// All 120 binary synthdef files from Sonic Pi

import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export const SYNTHDEFS_DIR = join(__dirname, 'synthdefs');

// Helper to get full path for a synthdef
export function getSynthDefPath(name) {
    return join(SYNTHDEFS_DIR, `${name}.scsyndef`);
}

// CDN URL for browser usage (unpkg)
export const CDN_BASE = 'https://unpkg.com/supersonic-scsynth-synthdefs@0.55.0';
export const SYNTHDEFS_CDN = `${CDN_BASE}/synthdefs`;

export const SYNTHDEF_NAMES = [
  "fft_brickwall",
  "fft_magfreeze",
  "fft_passthrough",
  "fft_size_1024",
  "fft_size_4096",
  "fft_size_512",
  "fft_test_sine",
  "simple_passthrough",
  "sonic-pi-amp_stereo_monitor",
  "sonic-pi-basic_mixer",
  "sonic-pi-basic_mono_player",
  "sonic-pi-basic_stereo_player",
  "sonic-pi-bass_foundation",
  "sonic-pi-bass_highend",
  "sonic-pi-beep",
  "sonic-pi-blade",
  "sonic-pi-bnoise",
  "sonic-pi-chipbass",
  "sonic-pi-chiplead",
  "sonic-pi-chipnoise",
  "sonic-pi-cnoise",
  "sonic-pi-dark_ambience",
  "sonic-pi-dpulse",
  "sonic-pi-dsaw",
  "sonic-pi-dtri",
  "sonic-pi-dull_bell",
  "sonic-pi-fm",
  "sonic-pi-fx_autotuner",
  "sonic-pi-fx_band_eq",
  "sonic-pi-fx_bitcrusher",
  "sonic-pi-fx_bpf",
  "sonic-pi-fx_compressor",
  "sonic-pi-fx_distortion",
  "sonic-pi-fx_echo",
  "sonic-pi-fx_eq",
  "sonic-pi-fx_flanger",
  "sonic-pi-fx_gverb",
  "sonic-pi-fx_hpf",
  "sonic-pi-fx_ixi_techno",
  "sonic-pi-fx_krush",
  "sonic-pi-fx_level",
  "sonic-pi-fx_lpf",
  "sonic-pi-fx_mono",
  "sonic-pi-fx_nbpf",
  "sonic-pi-fx_nhpf",
  "sonic-pi-fx_nlpf",
  "sonic-pi-fx_normaliser",
  "sonic-pi-fx_nrbpf",
  "sonic-pi-fx_nrhpf",
  "sonic-pi-fx_nrlpf",
  "sonic-pi-fx_octaver",
  "sonic-pi-fx_pan",
  "sonic-pi-fx_panslicer",
  "sonic-pi-fx_ping_pong",
  "sonic-pi-fx_pitch_shift",
  "sonic-pi-fx_rbpf",
  "sonic-pi-fx_record",
  "sonic-pi-fx_reverb",
  "sonic-pi-fx_rhpf",
  "sonic-pi-fx_ring_mod",
  "sonic-pi-fx_rlpf",
  "sonic-pi-fx_scope_out",
  "sonic-pi-fx_slicer",
  "sonic-pi-fx_sound_out",
  "sonic-pi-fx_sound_out_stereo",
  "sonic-pi-fx_tanh",
  "sonic-pi-fx_tremolo",
  "sonic-pi-fx_vowel",
  "sonic-pi-fx_whammy",
  "sonic-pi-fx_wobble",
  "sonic-pi-gabberkick",
  "sonic-pi-gnoise",
  "sonic-pi-growl",
  "sonic-pi-hollow",
  "sonic-pi-hoover",
  "sonic-pi-kalimba",
  "sonic-pi-live_audio",
  "sonic-pi-live_audio_mono",
  "sonic-pi-live_audio_stereo",
  "sonic-pi-mixer",
  "sonic-pi-mod_dsaw",
  "sonic-pi-mod_fm",
  "sonic-pi-mod_pulse",
  "sonic-pi-mod_saw",
  "sonic-pi-mod_sine",
  "sonic-pi-mod_tri",
  "sonic-pi-mono_player",
  "sonic-pi-noise",
  "sonic-pi-organ_tonewheel",
  "sonic-pi-piano",
  "sonic-pi-pluck",
  "sonic-pi-pnoise",
  "sonic-pi-pretty_bell",
  "sonic-pi-prophet",
  "sonic-pi-pulse",
  "sonic-pi-recorder",
  "sonic-pi-rhodey",
  "sonic-pi-rodeo",
  "sonic-pi-saw",
  "sonic-pi-sc808_bassdrum",
  "sonic-pi-sc808_clap",
  "sonic-pi-sc808_claves",
  "sonic-pi-sc808_closed_hihat",
  "sonic-pi-sc808_congahi",
  "sonic-pi-sc808_congalo",
  "sonic-pi-sc808_congamid",
  "sonic-pi-sc808_cowbell",
  "sonic-pi-sc808_cymbal",
  "sonic-pi-sc808_maracas",
  "sonic-pi-sc808_open_hihat",
  "sonic-pi-sc808_rimshot",
  "sonic-pi-sc808_snare",
  "sonic-pi-sc808_tomhi",
  "sonic-pi-sc808_tomlo",
  "sonic-pi-sc808_tommid",
  "sonic-pi-scope",
  "sonic-pi-server-info",
  "sonic-pi-sound_in",
  "sonic-pi-sound_in_stereo",
  "sonic-pi-square",
  "sonic-pi-stereo_player",
  "sonic-pi-subpulse",
  "sonic-pi-supersaw",
  "sonic-pi-tb303",
  "sonic-pi-tech_saws",
  "sonic-pi-tri",
  "sonic-pi-zawa",
  "test_offset_out",
];

export default {
    SYNTHDEFS_DIR,
    getSynthDefPath,
    CDN_BASE,
    SYNTHDEFS_CDN,
    SYNTHDEF_NAMES
};
