#!/bin/bash

# Build script for Supersonic
# Compiles C++ to WebAssembly using Emscripten

set -e

# Check for release mode flag
RELEASE_MODE=false
if [ "$1" = "--release" ]; then
    RELEASE_MODE=true
    echo "Building in RELEASE mode (no cache-busted WASM)"
else
    echo "Building in DEV mode (includes cache-busted WASM for local development)"
fi
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
SRC_DIR="$PROJECT_ROOT/src"
JS_DIR="$PROJECT_ROOT/js"
OUTPUT_DIR="$PROJECT_ROOT/dist"

echo "Building Supersonic..."
echo "Source: $SRC_DIR"
echo "Output: $OUTPUT_DIR"

# Create output directories if they don't exist
mkdir -p "$OUTPUT_DIR/wasm"

# Check if emcc is available
if ! command -v emcc &> /dev/null; then
    echo "Error: emcc (Emscripten compiler) not found!"
    echo "Please install and activate the Emscripten SDK first:"
    echo "  https://emscripten.org/docs/getting_started/downloads.html"
    echo ""
    echo "Then run: source <path-to-emsdk>/emsdk_env.sh"
    exit 1
fi

echo "Using Emscripten version:"
emcc --version | head -1

# Generate unique build ID that changes per build (for cache busting)
BUILD_ID=$(date -u +"%Y%m%d-%H%M%S")  # e.g., "20251029-120235"
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Create build_info.h before compilation
cat > "$SRC_DIR/build_info.h" << EOF
// Auto-generated by build.sh - DO NOT EDIT
#ifndef BUILD_INFO_H
#define BUILD_INFO_H
#define BUILD_HASH "$BUILD_ID"
#define BUILD_TIME "$BUILD_TIME"
#define GIT_HASH "$GIT_HASH"
#endif
EOF

# Build standalone WASM with shared memory import and scsynth
echo "Compiling C++ to WASM with scsynth..."
echo "Build ID: $BUILD_ID (git: $GIT_HASH, time: $BUILD_TIME)"

# Calculate FIXED_MEMORY from memory_layout.js (ensures build/runtime sync)
# Memory is fixed (not growable) because we use SharedArrayBuffer for WASM/JS communication
echo "Reading memory configuration..."
FIXED_MEMORY=$(node scripts/get_memory_config.js)
if [ $? -ne 0 ]; then
    echo "Error: Failed to read memory configuration from js/memory_layout.js"
    exit 1
fi
echo "FIXED_MEMORY: $FIXED_MEMORY bytes ($((FIXED_MEMORY / 1024 / 1024))MB)"

# Scheduler configuration (override with environment variables if needed)
SCHEDULER_SLOT_SIZE=${SCHEDULER_SLOT_SIZE:-1024}
SCHEDULER_SLOT_COUNT=${SCHEDULER_SLOT_COUNT:-512}
SCHEDULER_MEMORY=$((SCHEDULER_SLOT_SIZE * SCHEDULER_SLOT_COUNT))
echo "SCHEDULER: $SCHEDULER_SLOT_COUNT slots × $SCHEDULER_SLOT_SIZE bytes = $((SCHEDULER_MEMORY / 1024))KB"

# Collect all scsynth source files
# Note: Platform-specific and unused files have been removed from the repo entirely
# (SC_ComPort.cpp, XenomaiLock.cpp, SC_PaUtils.cpp, sc_popen.cpp, strtod.c)
SCSYNTH_SERVER_SOURCES=$(find "$SRC_DIR/scsynth/server" -name "*.cpp" ! -name "SC_*Plugins.cpp" ! -name "scsynth_main.cpp" ! -name "SC_WebAudio.cpp" ! -name "SC_Wasm.cpp" ! -name "SC_WasmOscBuilder.cpp" 2>/dev/null | tr '\n' ' ')
SCSYNTH_COMMON_SOURCES=$(find "$SRC_DIR/scsynth/common" -name "*.cpp" 2>/dev/null | tr '\n' ' ')
SCSYNTH_COMMON_C_SOURCES=$(find "$SRC_DIR/scsynth/common" -name "*.c" 2>/dev/null | tr '\n' ' ')
SCSYNTH_PLUGIN_SOURCES=$(find "$SRC_DIR/scsynth/plugins" -name "*.cpp" 2>/dev/null | tr '\n' ' ')

# Compile audio processor with all scsynth sources and oscpack (standalone WASM for AudioWorklet)
# Note: Memory is fixed (ALLOW_MEMORY_GROWTH=0) because SharedArrayBuffer cannot be resized
emcc "$SRC_DIR/audio_processor.cpp" \
    "$SRC_DIR/buffer_commands.cpp" \
    "$SRC_DIR/node_tree.cpp" \
    "$SRC_DIR/scsynth/server/SC_OscUnroll.cpp" \
    $SCSYNTH_SERVER_SOURCES \
    $SCSYNTH_COMMON_SOURCES \
    $SCSYNTH_COMMON_C_SOURCES \
    $SCSYNTH_PLUGIN_SOURCES \
    "$SRC_DIR/vendor/oscpack/osc/OscTypes.cpp" \
    "$SRC_DIR/vendor/oscpack/osc/OscOutboundPacketStream.cpp" \
    "$SRC_DIR/vendor/oscpack/osc/OscReceivedElements.cpp" \
    -I"$SRC_DIR" \
    -I"$SRC_DIR/scsynth/include/common" \
    -I"$SRC_DIR/scsynth/include/plugin_interface" \
    -I"$SRC_DIR/scsynth/include/server" \
    -I"$SRC_DIR/scsynth/server" \
    -I"$SRC_DIR/scsynth/common" \
    -I"$SRC_DIR/scsynth/external_libraries/boost" \
    -I"$SRC_DIR/scsynth/external_libraries/nova-simd" \
    -I"$SRC_DIR/vendor/oscpack" \
    -DNO_LIBSNDFILE \
    -DNDEBUG \
    -DSCHEDULER_SLOT_SIZE=$SCHEDULER_SLOT_SIZE \
    -DSCHEDULER_SLOT_COUNT=$SCHEDULER_SLOT_COUNT \
    -DBOOST_ASIO_HAS_PTHREADS \
    -DSTATIC_PLUGINS \
    -DNOVA_SIMD \
    -DSC_FFT_GREEN \
    -sSTANDALONE_WASM \
    -sNO_FILESYSTEM=1 \
    -sENVIRONMENT=worker \
    -pthread \
    -sALLOW_MEMORY_GROWTH=0 \
    -sINITIAL_MEMORY=$FIXED_MEMORY \
    -sEXPORTED_FUNCTIONS="['___wasm_call_ctors','_get_ring_buffer_base','_get_buffer_layout','_init_memory','_process_audio','_get_audio_output_bus','_get_audio_buffer_samples','_get_supersonic_version_string','_set_time_offset','_get_time_offset','_worklet_debug','_worklet_debug_va','_get_process_count','_get_messages_processed','_get_messages_dropped','_get_status_flags']" \
    --no-entry \
    -Wl,--import-memory,--shared-memory,--allow-multiple-definition \
    -fcommon \
    -O3 \
    -fno-math-errno \
    -fsigned-zeros \
    -fno-associative-math \
    -Wno-nontrivial-memcall \
    -Wno-extern-c-compat \
    -msimd128 \
    -flto \
    -fwasm-exceptions \
    -sERROR_ON_UNDEFINED_SYMBOLS=0 \
    -o "$OUTPUT_DIR/wasm/scsynth-nrt.wasm"

# Generate WASM file hash for cache busting (dev mode only)
if [ "$RELEASE_MODE" = false ]; then
    echo "Generating WASM hash for cache busting..."

    # Clean up old cache-busted symlinks (8-char hash pattern)
    find "$OUTPUT_DIR/wasm" -type l -name "scsynth-nrt.????????.wasm" -delete 2>/dev/null || true

    WASM_HASH=$(sha256sum "$OUTPUT_DIR/wasm/scsynth-nrt.wasm" | cut -c1-8)
    WASM_FILENAME_VERSIONED="scsynth-nrt.$WASM_HASH.wasm"

    # Create symlink to hashed filename (for dev/example - forces cache refresh)
    ln -sf "scsynth-nrt.wasm" "$OUTPUT_DIR/wasm/$WASM_FILENAME_VERSIONED"

    # Create manifest with both file options
    cat > "$OUTPUT_DIR/wasm/manifest.json" << EOF
{
  "wasmFile": "$WASM_FILENAME_VERSIONED",
  "wasmFileStable": "scsynth-nrt.wasm",
  "hash": "$WASM_HASH",
  "buildId": "$BUILD_ID",
  "buildTime": "$BUILD_TIME",
  "gitHash": "$GIT_HASH"
}
EOF

    echo "WASM files:"
    echo "  Production:  scsynth-nrt.wasm (use with Cache-Control headers)"
    echo "  Development: $WASM_FILENAME_VERSIONED (cache-busted)"
else
    # Release mode - only create stable manifest
    cat > "$OUTPUT_DIR/wasm/manifest.json" << EOF
{
  "wasmFile": "scsynth-nrt.wasm",
  "buildId": "$BUILD_ID",
  "buildTime": "$BUILD_TIME",
  "gitHash": "$GIT_HASH"
}
EOF

    echo "WASM file:"
    echo "  scsynth-nrt.wasm (release build)"
fi
echo "Build: $BUILD_ID (git: $GIT_HASH)"

# Check if node_modules exists and install dependencies if needed
if [ ! -d "$PROJECT_ROOT/node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Check if esbuild is available
if ! command -v esbuild &> /dev/null; then
    echo "Error: esbuild not found!"
    echo "Please install esbuild: npm install"
    exit 1
fi

echo "Bundling JavaScript with esbuild..."

# Set __DEV__ flag and minification based on build mode
if [ "$RELEASE_MODE" = true ]; then
    DEV_FLAG="false"
    MINIFY_FLAG="--minify"
    echo "  __DEV__ = false (release mode - debug logs stripped, minified)"
else
    DEV_FLAG="true"
    MINIFY_FLAG=""
    echo "  __DEV__ = true (dev mode - debug logs enabled, readable)"
fi

# Bundle the main orchestrator (entry point for the library)
# osc.js is now a pure ES module (converted from UMD) and can be bundled
esbuild "$JS_DIR/supersonic.js" \
    --bundle \
    --format=esm \
    --define:__DEV__=$DEV_FLAG \
    $MINIFY_FLAG \
    --outfile="$OUTPUT_DIR/supersonic.js" \
    --external:./scsynth-nrt.wasm

# Process worker files through esbuild (separate output files, same __DEV__ treatment)
echo "Processing worker files..."
mkdir -p "$OUTPUT_DIR/workers"
for worker in "$JS_DIR/workers/"*.js; do
    worker_name=$(basename "$worker")
    esbuild "$worker" \
        --bundle \
        --format=iife \
        --define:__DEV__=$DEV_FLAG \
        $MINIFY_FLAG \
        --outfile="$OUTPUT_DIR/workers/$worker_name"
done

# Create symlinks to synthdefs and samples from packages
SYNTHDEFS_SRC="$PROJECT_ROOT/packages/supersonic-scsynth-synthdefs/synthdefs"
SAMPLES_SRC="$PROJECT_ROOT/packages/supersonic-scsynth-samples/samples"

if [ -d "$SYNTHDEFS_SRC" ]; then
    echo "Creating symlink to synthdefs..."
    rm -rf "$OUTPUT_DIR/synthdefs"
    ln -s "$SYNTHDEFS_SRC" "$OUTPUT_DIR/synthdefs"
    echo "Linked to $(ls -1 "$SYNTHDEFS_SRC/"*.scsyndef 2>/dev/null | wc -l) synthdef files"
else
    echo "Warning: synthdefs not found at $SYNTHDEFS_SRC"
fi

if [ -d "$SAMPLES_SRC" ]; then
    echo "Creating symlink to samples..."
    rm -rf "$OUTPUT_DIR/samples"
    ln -s "$SAMPLES_SRC" "$OUTPUT_DIR/samples"
    echo "Linked to $(ls -1 "$SAMPLES_SRC/" 2>/dev/null | wc -l) sample files"
else
    echo "Warning: samples not found at $SAMPLES_SRC"
fi

echo "Build complete!"
echo "Generated files:"
ls -lh "$OUTPUT_DIR"
