/*
 * test_ring_wire_conformance.cpp — replay the golden ring-wire corpus
 * (test/fixtures/ring_wire.txt) through the C++ ring implementation
 * (RingBufferWriter.h writer + ring_drain.h reader) and require
 * byte-identical results.
 *
 * The corpus is generated by the JS implementation
 * (scripts/gen-ring-fixtures.mjs over js/lib/ring_buffer_core.js) and also
 * replayed by test/unit/ring_wire_conformance.test.mjs. A change to either
 * implementation that alters the wire — framing, padding, alignment, cursor
 * advance — fails one of the two suites, so the implementations cannot
 * drift apart silently.
 */
#include <catch2/catch_test_macros.hpp>

#include "lanes/ring_drain.h"
#include "workers/RingBufferWriter.h"
#include "shared_memory.h"

#include <atomic>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#ifndef RING_WIRE_FIXTURE
#error "RING_WIRE_FIXTURE must point at test/fixtures/ring_wire.txt"
#endif

namespace {

std::string toHex(const uint8_t* p, size_t n) {
    static const char* d = "0123456789abcdef";
    std::string s;
    s.reserve(n * 2);
    for (size_t i = 0; i < n; ++i) {
        s += d[p[i] >> 4];
        s += d[p[i] & 0xF];
    }
    return s;
}

std::vector<uint8_t> fromHex(const std::string& s) {
    std::vector<uint8_t> v;
    v.reserve(s.size() / 2);
    for (size_t i = 0; i + 1 < s.size(); i += 2)
        v.push_back(static_cast<uint8_t>(std::stoul(s.substr(i, 2), nullptr, 16)));
    return v;
}

struct WireOp {
    bool                 isWrite = false;
    uint32_t             sourceId = 0;
    std::vector<uint8_t> payload;
    std::string          expect;     // "ok" | "full"
    uint32_t             drainMax = 0;
};

struct WireMsg {
    uint32_t    seq = 0, sourceId = 0;
    std::string payloadHex;
    bool operator==(const WireMsg& o) const {
        return seq == o.seq && sourceId == o.sourceId && payloadHex == o.payloadHex;
    }
};

struct WireCase {
    std::string          name;
    uint32_t             size = 0;
    std::vector<WireOp>  ops;
    std::vector<WireMsg> msgs;
    int32_t              head = 0, tail = 0;
    std::string          imageHex;
};

std::vector<WireCase> loadCorpus() {
    std::ifstream in(RING_WIRE_FIXTURE);
    REQUIRE(in.good());

    std::vector<WireCase> cases;
    WireCase cur;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ls(line);
        std::string kw;
        ls >> kw;
        if (kw == "case") {
            cur = WireCase{};
            ls >> cur.name;
        } else if (kw == "size") {
            ls >> cur.size;
        } else if (kw == "write") {
            WireOp op;
            op.isWrite = true;
            std::string hex;
            ls >> op.sourceId >> hex >> op.expect;
            op.payload = fromHex(hex);
            cur.ops.push_back(std::move(op));
        } else if (kw == "drain") {
            WireOp op;
            ls >> op.drainMax;
            cur.ops.push_back(std::move(op));
        } else if (kw == "msg") {
            WireMsg m;
            ls >> m.seq >> m.sourceId >> m.payloadHex;  // payload may be empty
            cur.msgs.push_back(std::move(m));
        } else if (kw == "head") {
            ls >> cur.head;
        } else if (kw == "tail") {
            ls >> cur.tail;
        } else if (kw == "image") {
            ls >> cur.imageHex;
        } else if (kw == "end") {
            cases.push_back(std::move(cur));
        }
    }
    return cases;
}

}  // namespace

TEST_CASE("ring wire conformance (C++): golden corpus replays byte-identically",
          "[lanes][conformance]") {
    auto cases = loadCorpus();
    REQUIRE(cases.size() >= 5);

    for (const auto& c : cases) {
        INFO("case " << c.name);
        std::vector<uint8_t> buf(c.size, 0);
        std::atomic<int32_t> head{0}, tail{0}, seq{0}, lock{0};
        SsDrainState st;
        std::vector<WireMsg> got;

        for (const auto& op : c.ops) {
            if (op.isWrite) {
                bool ok = RingBufferWriter::write(
                    buf.data(), c.size, &head, &tail, &seq, &lock,
                    op.payload.data(), static_cast<uint32_t>(op.payload.size()),
                    op.sourceId);
                INFO("write src=" << op.sourceId << " len=" << op.payload.size());
                CHECK(ok == (op.expect == "ok"));
            } else {
                ss_drain_ring(buf.data(), c.size, &head, &tail, st,
                              SsDrainMetrics{}, op.drainMax,
                              [&](uint32_t src, const uint8_t* p, uint32_t n,
                                  uint32_t s) {
                                  got.push_back({s, src, toHex(p, n)});
                                  return SsDrainVerdict::Consume;
                              });
            }
        }

        CHECK(got == c.msgs);
        CHECK(head.load() == c.head);
        CHECK(tail.load() == c.tail);
        CHECK(toHex(buf.data(), buf.size()) == c.imageHex);
    }
}
