// GENERATED by scripts/gen-scsynth-options.mjs from dsp/scsynth/scsynth_options.h.
// Do not edit: change the header and regenerate. test/scsynth_options_schema.spec.mjs
// fails when this file and the header disagree.
//
// The options scsynth takes from a host: name, the scsynth command-line
// letter, default, range and a line of documentation. The client's defaults,
// validation and the "name=value" block it sends all come from here.
export const scsynthOptionSchema = Object.freeze([
  { name: "numBuffers", flag: "b", default: 1024, min: 1, max: 65535, doc: "Sample buffers (SndBuf slots)" },
  { name: "maxNodes", flag: "n", default: 1024, min: 1, max: 4194304, doc: "Nodes (synths and groups) that may exist at once" },
  { name: "maxGraphDefs", flag: "d", default: 1024, min: 1, max: 4194304, doc: "Synth definitions that may be loaded at once" },
  { name: "maxWireBufs", flag: "w", default: 64, min: 1, max: 4194304, doc: "Wire buffers for a synth's internal connections" },
  { name: "numAudioBusChannels", flag: "a", default: 1024, min: 1, max: 4194304, doc: "Audio bus channels" },
  { name: "numControlBusChannels", flag: "c", default: 16384, min: 1, max: 16777216, doc: "Control bus channels" },
  { name: "realTimeMemorySize", flag: "m", default: 8192, min: 1, max: 4194304, doc: "Real-time memory pool, in KB" },
  { name: "numRGens", flag: "r", default: 64, min: 1, max: 65536, doc: "Random number generators" },
  { name: "loadGraphDefs", flag: "D", default: 0, min: 0, max: 1, doc: "Load synth definitions from the synthdef directory at boot (1) or not (0)" },
  { name: "verbosity", flag: "V", default: 0, min: 0, max: 4, doc: "How much the engine prints; 0 is quiet" },
]);
export default scsynthOptionSchema;
